"""add timestamp to NFT

Revision ID: ce1ddfe5ba0f
Revises: 9d3144d6774d
Create Date: 2025-04-07 14:45:19.755067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce1ddfe5ba0f'
down_revision: Union[str, None] = '9d3144d6774d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nft', sa.Column('timestamp', sa.DateTime(), nullable=False, server_default="2025-06-30 14:19:54"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nft', 'timestamp')
    # ### end Alembic commands ###
